[package]
name = "benchmark-receiver"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tonic = { version = "0.10", features = ["tls"] }
prost = "0.12"

[build-dependencies]
tonic-build = "0.10"